language: python
python:
  - 2.7
  - 3.5
env:
  - DJANGO_SETTINGS_MODULE=test.conf
  - DJANGO=1.8
  - DJANGO=1.9
install:
  - pip install -q Django==$DJANGO django-debug-toolbar>=1.0
script: python -m tests.test_toolbar